import kette from "./assets/kette.webp";

export const products = [
  {
    id: 1,
    name: "GoldRing",
    material: "gold",
    type: "ring",
    price: 150,
    description: "A beautiful gold ring with a diamond accent.",
    Image: kette,
  },
  {
    id: 2,
    name: "SilverRing",
    material: "silver",
    type: "ring",
    price: 200,
    description: "A beautiful silver ring with a diamond accent.",
    Image: "",
  },
  {
    id: 3,
    name: "Silver Nacklace",
    material: "silver",
    type: "nack",
    price: 130,
    description: "A beautiful silver Nack.",
    Image: "",
  },
  {
    id: 4,
    name: "Platinum Ring",
    material: "Platinum",
    type: "ring",
    price: 130,
    description: "A beautiful Plartinum Ring with a diamond accent.",
    Image: "",
  },
  {
    id: 5,
    name: "Gold Nacklace",
    material: "gold",
    type: "ring",
    price: 130,
    description: "A beautiful gold Nack.",
    Image: "",
  },
  {
    id: 6,
    name: "Platinum Nacklace",
    material: "Platinum",
    type: "ring",
    price: 130,
    description: "A beautiful platinum Nack .",
    Image: "",
  },
  {
    id: 7,
    name: "Tank Ring",
    material: "silver",
    type: "ear",
    price: 130,
    description: "A beautiful silver chain link ring.",
    Image: "",
  },
  {
    id: 8,
    name: "Tank Ring",
    material: "gold",
    type: "ring",
    price: 130,
    description: "A beautiful gold chain link ring.",
    Image: "",
  },
  {
    id: 9,
    name: "Silver Nacklace",
    material: "silver",
    type: "ring",
    price: 130,
    description: "A beautiful silver Nack with a diamond accent.",
    Image: "",
  },
  {
    id: 10,
    name: "Silver Nacklace",
    material: "silver",
    type: "ring",
    price: 130,
    description: "A beautiful silver Nack with a diamond accent.",
    Image: "",
  },
];
